name: Heirloom
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ARM64, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $global:ErrorActionPreference = "Stop"
          $global:ProgressPreference = "SilentlyContinue"

          # vswhere is slow, check this hardcoded path first.
          $msbuild = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          if (-not (Test-Path $msbuild))
          {
            Write-Host "Checking for vswhere.exe"
            $vswhere = Join-Path "$env:ProgramFiles (x86)" "Microsoft Visual Studio\Installer\vswhere.exe"
            if (-not (Test-Path $vswhere))
            {
                throw "Could not find vswhere.exe"
            }
            Write-Host "vswhere: $vswhere"

            Write-Host "Checking for msbuild.exe"
            $msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -First 1
            if (-not (Test-Path $msbuild))
            {
                throw "Could not find msbuild.exe"
            }
          }
          Write-Host "msbuild: $msbuild"

          Push-Location src

          #
          # Winfile
          #

          Write-Host "Winfile: Building for ${{ matrix.platform }}"
          & $msbuild winfile.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }} /verbosity:quiet /nologo
          if ($LASTEXITCODE -ne 0)
          {
              throw "Winfile: Failed to build for ${{ matrix.platform }}"
          }

          #
          # Progman
          #

          Write-Host "Progman: Building for ${{ matrix.platform }}"
          & $msbuild progman.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }} /verbosity:quiet /nologo
          if ($LASTEXITCODE -ne 0)
          {
              throw "Progman: Failed to build for ${{ matrix.platform }}"
          }

          Pop-Location

          Write-Host "Creating artifacts directory"
          New-Item -ItemType Directory -Path . -Name stage
          New-Item -ItemType Directory -Path stage -Name ${{ matrix.platform }}

          Copy-Item src\winfile\LICENSE stage\${{ matrix.platform }}\LICENSE-winfile.txt
          Copy-Item src\winfile\${{ matrix.platform }}\Release\winfile.exe stage\${{ matrix.platform }}\winfile.exe

          Copy-Item src\progman\LICENSE stage\${{ matrix.platform }}\LICENSE.txt
          Copy-Item src\progman\${{ matrix.platform }}\Release\progman.exe stage\${{ matrix.platform }}\progman.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: winfile-${{ matrix.platform }}
          path: stage/${{ matrix.platform }}
